### PR TITLE
Code Modified

### PR DESCRIPTION
**Pull request by prans7**
Spaces reduced

### CODE REVIEW

**Comment by prans7** [comment]
> noko mala changes

ja tikda pathvanar nahi tula me kahi atta pasun

**Comment by sumeetgodse** [comment]
kk

**Comment by prans7** [comment]
> kk

ok

**Comment by sumeetgodse** [comment]
> > kk
> 
> ok

k

**Comment by prans7** [comment]
> > > kk
> > 
> > 
> > ok
> 
> k

bas bhava

**Comment by sumeetgodse** [comment]
> > > > kk
> > > 
> > > 
> > > ok
> > 
> > 
> > k
> 
> bas bhava

k

**Pull request closed without merging**
